#!/usr/bin/env bash
# Per-runtime emitter: codex-app (web).
# Sourced by scripts/sync-runtimes.sh. Helpers come from 00-helpers.sh.

emit_codex_app() {
  [ "$DRY_RUN" -eq 0 ] && yellow "[codex-app] mirror of skills/ + commands/ with Codex App upload notes"
  prune_runtime_dist "codex-app"
  mirror_canonical_files "codex-app"
  write_or_announce_heredoc "dist/codex-app/MANIFEST.md" <<'EOF'
# hackify — Codex App (web) package

The Codex App accepts custom instructions and uploaded reference documents.
Hackify is shipped here as a set of markdown files you upload as project
context.

## Install

1. Open your project in the Codex App and go to Settings -> Custom
   Instructions / Project Files.
2. Upload `skills/hackify/SKILL.md` as the primary instruction set.
3. Upload everything under `skills/hackify/references/` as supporting
   reference documents (Codex App will let the model retrieve them by name).
4. Optionally upload the companion skill files (`groom`,
   `skillsmith`, `review-triage`, `quick`) the same way.
5. Paste the body of `commands/summary.md` into a Codex App "saved prompt"
   slot if you want a one-click summary trigger.

## Contents

Same as `dist/codex-cli/` — the canonical hackify file tree.

## Source of truth

Regenerated by `scripts/sync-runtimes.sh` from the canonical repo sources.
EOF
}
