#!/usr/bin/env bash
# Per-runtime emitter: codex-cli.
# Sourced by scripts/sync-runtimes.sh. Helpers come from 00-helpers.sh.

emit_codex_cli() {
  [ "$DRY_RUN" -eq 0 ] && yellow "[codex-cli] mirror of skills/ + commands/ with Codex CLI install notes"
  prune_runtime_dist "codex-cli"
  mirror_canonical_files "codex-cli"
  write_or_announce_heredoc "dist/codex-cli/MANIFEST.md" <<'EOF'
# hackify — Codex CLI package

Codex CLI loads prompts from `~/.codex/prompts/`. Hackify is shipped as a
collection of skill markdown files plus a slash-command body.

## Install

1. Copy the contents of this directory's `skills/` and `commands/` into
   `~/.codex/prompts/hackify/` (preserve subdirectory structure).
2. Restart Codex CLI so the prompt index is rebuilt.
3. Invoke the workflow by referencing `hackify/SKILL.md` (or the per-skill
   SKILL.md for `quick`, `groom`, etc.) in your prompt.

## Contents

- `skills/hackify/SKILL.md` — the universal end-to-end dev workflow.
- `skills/hackify/references/` — sub-agent and wizard prompt templates.
- `skills/hackify/evals/evals.json` — eval cases.
- `skills/groom/SKILL.md`, `skills/skillsmith/SKILL.md`,
  `skills/review-triage/SKILL.md`, `skills/quick/SKILL.md` — companions.
- `commands/summary.md` — body for the `/hackify:summary` shortcut (Codex CLI
  has no native slash-command registry; paste the body when needed).

## Source of truth

Regenerated by `scripts/sync-runtimes.sh` from the canonical repo sources.
EOF
}
