#!/usr/bin/env bash
# Per-runtime emitter: copilot-cli (MANIFEST-only — no plugin model).
# Sourced by scripts/sync-runtimes.sh. Helpers come from 00-helpers.sh.

emit_copilot_cli() {
  [ "$DRY_RUN" -eq 0 ] && yellow "[copilot-cli] MANIFEST.md only — no plugin model"
  prune_runtime_dist "copilot-cli"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run] WOULD WRITE: %s\n' "dist/copilot-cli/MANIFEST.md"
    FILE_COUNT=$((FILE_COUNT + 1))
    return 0
  fi
  if [ ! -f "skills/hackify/SKILL.md" ]; then
    red "  MISS skills/hackify/SKILL.md — cannot build copilot-cli MANIFEST.md"
    FAILED=$((FAILED + 1))
    return 1
  fi
  if ! mkdir -p "dist/copilot-cli"; then
    red "  FAIL mkdir -p dist/copilot-cli"
    FAILED=$((FAILED + 1))
    return 1
  fi
  {
    cat <<'HEADER'
# hackify — GitHub Copilot CLI package

GitHub Copilot CLI has NO plugin / skill / custom-instruction model as of
hackify v0.2.0. You cannot register hackify as a reusable workflow; the
only integration path is to paste the SKILL.md body into a Copilot CLI
prompt manually each time you start a task.

## Disclaimer

This runtime is supported on a best-effort basis. If GitHub ships a plugin
or persistent-instructions model in the future, hackify will add proper
integration; until then, treat this MANIFEST.md as the only deliverable for
copilot-cli and copy the body below into your Copilot CLI session as
needed.

## How to use

1. Open a Copilot CLI session in your project.
2. Paste everything between the `===== BEGIN SKILL.md =====` and
   `===== END SKILL.md =====` markers below as your initial prompt.
3. Follow the workflow steps the SKILL.md prescribes (clarification gate,
   plan gate, implementation, verification, review).
4. For the companion skills (`quick`, `groom`, etc.) repeat the same
   paste-on-demand pattern with their SKILL.md bodies from the canonical
   `skills/<name>/SKILL.md`.

===== BEGIN SKILL.md =====
HEADER
    cat skills/hackify/SKILL.md
    cat <<'FOOTER'
===== END SKILL.md =====

## Source of truth

Regenerated by `scripts/sync-runtimes.sh` from the canonical repo sources.
FOOTER
  } > "dist/copilot-cli/MANIFEST.md"
  if [ $? -eq 0 ]; then
    FILE_COUNT=$((FILE_COUNT + 1))
  else
    red "  FAIL write dist/copilot-cli/MANIFEST.md"
    FAILED=$((FAILED + 1))
  fi
}
