#!/usr/bin/env bash
# Per-runtime emitter: cursor.
# Sourced by scripts/sync-runtimes.sh. Helpers come from 00-helpers.sh.

emit_cursor() {
  [ "$DRY_RUN" -eq 0 ] && yellow "[cursor] mirror + .mdc porting notes"
  prune_runtime_dist "cursor"
  mirror_canonical_files "cursor"
  write_or_announce_heredoc "dist/cursor/MANIFEST.md" <<'EOF'
# hackify — Cursor package

Cursor rules live under `.cursor/rules/` as `.mdc` files. v0.2.0 does NOT
ship an automatic markdown -> `.mdc` adapter; the markdown files here are
copy-paste-ready bodies you can wrap in a minimal `.mdc` frontmatter.

## Install (manual port)

1. For each skill SKILL.md you want to use, create a corresponding `.mdc`
   under `.cursor/rules/`, for example `.cursor/rules/hackify.mdc`.
2. Add minimal Cursor rule frontmatter at the top of each `.mdc`:

       ---
       description: hackify — universal end-to-end dev workflow
       globs: "**/*"
       alwaysApply: false
       ---

3. Paste the full body of the corresponding `SKILL.md` below the
   frontmatter.
4. Repeat for any references under `skills/hackify/references/` that you
   want Cursor to load eagerly (most can stay markdown and be referenced on
   demand from the main rule).

## Why no auto-adapter

Cursor's `.mdc` schema is small but version-sensitive and globs require
project-specific tuning. v0.2.0 keeps the port manual to avoid shipping a
brittle adapter that breaks on Cursor schema updates. A scripted adapter is
a candidate for a future minor version.

## Contents

Mirror of the canonical hackify file tree, ready for manual porting.

## Source of truth

Regenerated by `scripts/sync-runtimes.sh` from the canonical repo sources.
EOF
}
