#!/usr/bin/env bash
# Per-runtime emitter: opencode.
# Sourced by scripts/sync-runtimes.sh. Helpers come from 00-helpers.sh.

emit_opencode() {
  [ "$DRY_RUN" -eq 0 ] && yellow "[opencode] mirror + custom-mode install notes"
  prune_runtime_dist "opencode"
  mirror_canonical_files "opencode"
  write_or_announce_heredoc "dist/opencode/MANIFEST.md" <<'EOF'
# hackify — OpenCode package

OpenCode supports custom modes via markdown files. Hackify is shipped here
as a set of mode-style markdown files plus reference documents.

## Install (custom mode)

1. Open OpenCode -> Modes -> New custom mode (or edit `~/.opencode/modes/`).
2. Create a mode named `hackify` and paste the body of
   `skills/hackify/SKILL.md` as the mode prompt.
3. Add the reference files from `skills/hackify/references/` as attachments
   or auxiliary context (OpenCode will load them on demand when the mode
   prompt references them).
4. Repeat for the companion skills (`quick`, `groom`,
   `skillsmith`, `review-triage`) if you want them available as
   separate modes.

## Contents

Mirror of the canonical hackify file tree (same as codex-cli).

## Source of truth

Regenerated by `scripts/sync-runtimes.sh` from the canonical repo sources.
EOF
}
