# shellcheck shell=bash

# THE PHASE 5 REVIEWER RENAME, PINNED FROM BOTH ENDS, on the shape
# 73-implementer-rename.sh built for check [40] and for the same reason. That
# block's header records the incident: commit dabc333 renamed the implementer
# agent, left every dispatch site naming a type that no longer existed, and the
# tree stayed fully green through a tagged release, because an agent type is
# resolved by the harness at DISPATCH time, long after the validator has had its
# say. Nothing in this repo greps an agent-type string on its own.
#
# WHICH RENAME IS POLICED HERE. 0.18.0 made the merged all-lens reviewer the
# default route in every mode, which retired the word "merged": it only ever
# meant something while there was a panel to merge FROM. So all six reviewer
# agents became one family and every one of them moved:
#
#     code-reviewer-merged        -> reviewer
#     code-reviewer-security      -> reviewer-security
#     code-reviewer-quality-plan  -> reviewer-quality-plan
#     code-reviewer-performance   -> reviewer-performance
#     code-reviewer-coherence     -> reviewer-coherence
#     design-conformance-reviewer -> reviewer-design
#
# `finding-refuter` is not a reviewer and did not move; neither did any other
# agent. The agents/*.md filenames moved with the types.
#
# WHY THIS IS A SEPARATE BLOCK FROM [40] RATHER THAN SIX MORE LITERALS IN IT.
# [40]'s scope excludes docs/work/* and CHANGELOG.md wholesale and its own
# fragment path, and every one of those rows is argued there for the IMPLEMENTER
# rename specifically. Feeding six unrelated literals through that block would
# inherit an exclusion set nobody re-argued and would leave one hand-written size
# bound policing two renames that move on different schedules. The seam is
# responsibility, the same seam 71's and 73's headers argue for.
#
# WHAT THIS BLOCK IS NOT. [30] in 60-primitives.sh counts agents/ against a list
# and matches each file's frontmatter `name:`; [87] reads the dispatch roster in
# parallel-agents/README.md from both ends against agents/. Both are roster
# checks and both discover their own sets, so both moved with this rename for
# free and neither noticed it happened. That is exactly the gap here: a rename is
# invisible to a check that reads the tree's CURRENT shape, because the current
# shape is self-consistent whether or not the rename finished. Only a scan for
# the DEAD name can tell a finished rename from a half-finished one.
#
# ---------------------------------------------------------------------------
# THE ABSENT HALF IS THE LOAD-BEARING ONE, and it is why the scan roots are wide.
# A rename across twenty-seven files is exactly where one quiet survivor hides in
# a file nobody thought to open, and a check that reads only the files the rename
# touched cannot catch what the rename missed. So the scan reads the whole tree
# under the pathspec below, not a hand-written site list.
#
# THE EXCLUDED PATHS ARE THE ONES ALLOWED TO SAY THE OLD WORDS, and each row is
# a claim about what is really in it rather than a glob thrown at a red.
#
#   dist/*          generated by scripts/sync-runtimes.sh from the canonical
#                   trees this block already scans, so a hit there is a stale
#                   build and check [56] is the instrument that says so.
#   docs/work/*     the sprint record. An archived work-doc under docs/work/done/
#                   quotes the tree as it stood, and rewriting one to green a
#                   check would be falsifying the record the check exists to
#                   protect. THE LIVE DOC IS THE SAME CLASS AND THE ROW COVERS IT
#                   DELIBERATELY: a work-doc that carries out a rename cannot
#                   describe its own task without naming what it renamed, so a
#                   narrower row stopping at done/ would force the next rename's
#                   author to reword their own backlog to keep this green. That
#                   is the same falsification one directory up. [98] and [99]
#                   already police work-doc content from their own angles.
#   CHANGELOG.md    release history, which has to be able to name what was
#                   renamed. THIS ROW WAIVES REAL OCCURRENCES, measured rather
#                   than assumed: 9 survive in shipped entries at the time of
#                   writing, from 0.13.0's reviewer merge down to 0.9.x, and
#                   every one of them is a sentence that cannot be written
#                   without the old name. It also waives the UNRELEASED entry at
#                   the top, which is a real cost and is stated rather than
#                   hidden; the same cost [40]'s CHANGELOG row carries and
#                   records.
#   this fragment   it holds the very literals it bans. [40]'s self-exclusion
#                   travelled with it through two file splits and its header
#                   warns whoever moves it next; the same warning applies to the
#                   path below. A [89] that moved house while that path stayed
#                   behind would red on its own text in the middle of the move.
#
# ':(top)' IS THE POSITIVE HALF AND IT IS NOT DECORATION, for the reason [40]
# states: a pathspec list made of nothing but exclusions is one reading away from
# resolving to no files at all, and a scan over no files prints green forever.
# 'top' also anchors every entry to the repo root rather than to the caller's
# working directory.
#
# ---------------------------------------------------------------------------
# THE SCAN READS UNTRACKED FILES TOO, WHICH IS WHERE THIS DIVERGES FROM [40], and
# the divergence is measured rather than stylistic. [40] scans tracked paths and
# argues untracked ones buy no coverage because [55] already reds on an
# uncommitted file under skills/, agents/ and hooks/. That argument has a hole
# this rename walked straight into: [55] does not cover scripts/, and the sprint
# that shipped this block had SEVEN untracked files under scripts/ at the moment
# the rename ran. A tracked-only scan would have greened over a dead name in any
# of them. `--untracked` closes that at the price of one flag, and it honours
# .gitignore, so build output and local scratch stay out of the scan the same way
# they stay out of [55]'s discovery.
#
# AND IT DOES NOT READ THE INDEX, WHICH IS THE OTHER DIVERGENCE. [40] unions a
# --cached scan onto its worktree scan to catch a mid-rename `rm <file>` that was
# never staged. That half is wrong for THIS check, and the number is what settles
# it: run over this repository at the commit that finished the rename, the
# --cached scan returned 10 files, and all 10 were files whose WORKTREE copy was
# already correct and whose index still held the pre-rename blob because the wave
# had not been committed yet. A rename lives its whole life in that pre-commit
# window, so a --cached half would make this block red for the entire time it is
# the only thing watching, and the only way to green it would be to stop trusting
# it. In CI the index and the worktree are identical, so that half would change
# no verdict there either. What it would have caught instead is covered twice
# over: the old agents/ paths are asserted ABSENT FROM DISK below, [30] counts
# agents/ against its own roster, and [55] reds on an uncommitted file under
# agents/.

yellow "[89] the Phase 5 reviewer rename, live names present and dead names absent"

# ---------------------------------------------------------------------------
# PRESENT, PART ONE: THE DISPATCH SITES.
#
# Every file that tells a dispatcher which type to send, or teaches the dispatch
# in prose a reader follows. A rename that reached the roster while missing the
# prose leaves a reader dispatching a type that no longer resolves, which is the
# 0.15.0 incident [40] was built for.
#
# THE TOKEN CARRIES ITS CLOSING BACKTICK ON PURPOSE. Bare 'hackify:reviewer' is a
# PREFIX of all five lens types, so a file naming only `hackify:reviewer-security`
# would satisfy a bare pin while saying nothing about the default reviewer. The
# backticked form is the exact one every site below writes, and it is the only
# form that distinguishes the merged type from its five siblings.
#
# The size is hand-written beside the list, the shape [40], [77] and [80] all use:
# a bound read back out of the list it polices cannot police that list. Drop a
# site and the element count drops with it, so that site's own check leaves the
# run and the run stays green one check shorter.
# EVERY RED THIS BLOCK PRINTS NAMES [89], the presence reds included, which is
# why the two loops below call a local matcher instead of the shared presence
# helper in 00-helpers.sh. That helper's red is worded for a reader looking at
# the transcript with the yellow header still in view; this bar prints roughly
# 1900 lines, and the first thing anyone does with a red is grep for it, at which
# point a message carrying no check id has to be routed by counting backwards to
# the nearest header. The absent half below already names itself on every branch,
# so the block would otherwise be half attributable. The test is the same
# one-line fixed-string match against a FILE, never a pipe, which is what keeps
# it clear of check [84]; only the wording differs, and the ok line names the
# check for the same reason the red does.
rrn_present() {
  local token="$1" path="$2"
  if grep -qF -- "$token" "$path" 2>/dev/null; then
    green "  ok   [89] '$token' present in $path"
  else
    red "  FAIL [89] '$token' is missing from $path, a site that dispatches or teaches the Phase 5 reviewer; the rename reached the roster and left this reader following a type that no longer resolves"
    FAILED=$((FAILED + 1))
  fi
}

RRN_SITES=('README.md' 'skills/hackify/SKILL.md' 'skills/quick/SKILL.md')
RRN_SITES+=('skills/review-triage/SKILL.md')
RRN_SITES+=('skills/hackify/references/review-and-verify.md')
RRN_SITES+=('skills/hackify/references/phases/phase-5-review.md')
RRN_SITES+=('skills/hackify/references/parallel-agents/README.md')
RRN_SITES+=('skills/hackify/references/parallel-agents/phase-5-escalation.md')
check_list_size "${#RRN_SITES[@]}" 8 "the [89] dispatch-site file set"
for f in "${RRN_SITES[@]}"; do rrn_present '`hackify:reviewer`' "$f"; done

# ---------------------------------------------------------------------------
# PRESENT, PART TWO: THE ROSTER ROW PER LENS.
#
# The five panel lenses are named in exactly one live file, the dispatch roster a
# dispatcher reads instead of opening a template. [87] already checks that every
# row resolves to a registered type and that every registered type has exactly
# one row, but it discovers both sides per run, so it is satisfied by any
# self-consistent naming. These five pins are what make the roster's names the
# RENAMED ones rather than merely consistent ones.
RRN_ROSTER='skills/hackify/references/parallel-agents/README.md'
RRN_LENS=('hackify:reviewer-security' 'hackify:reviewer-quality-plan')
RRN_LENS+=('hackify:reviewer-performance' 'hackify:reviewer-coherence')
RRN_LENS+=('hackify:reviewer-design')
check_list_size "${#RRN_LENS[@]}" 5 "the [89] panel-lens type list"
for t in "${RRN_LENS[@]}"; do rrn_present "$t" "$RRN_ROSTER"; done

# ---------------------------------------------------------------------------
# PRESENT, PART THREE: THE SIX DEFINITION FILES, AND THE SIX OLD PATHS GONE.
#
# Both directions, because each catches what the other cannot. A missing new file
# is a dispatch that resolves to nothing. An old file still on disk is the half
# of a half-finished rename that every OTHER check in this tree reads as healthy:
# [30] counts agents/*.md against a roster and would red on eleven files, but a
# rename done by COPY rather than by move leaves the copy behind and [30]'s count
# is the only thing between that and a green bar. Asserting the old path absent
# from disk says it directly.
RRN_AGENTS=('reviewer' 'reviewer-security' 'reviewer-quality-plan')
RRN_AGENTS+=('reviewer-performance' 'reviewer-coherence' 'reviewer-design')
check_list_size "${#RRN_AGENTS[@]}" 6 "the [89] live reviewer definition list"
for n in "${RRN_AGENTS[@]}"; do check_file "agents/${n}.md"; done

RRN_OLD_AGENTS=('code-reviewer-merged' 'code-reviewer-security')
RRN_OLD_AGENTS+=('code-reviewer-quality-plan' 'code-reviewer-performance')
RRN_OLD_AGENTS+=('code-reviewer-coherence' 'design-conformance-reviewer')
check_list_size "${#RRN_OLD_AGENTS[@]}" 6 "the [89] retired reviewer definition list"
for n in "${RRN_OLD_AGENTS[@]}"; do
  if [ -e "agents/${n}.md" ]; then
    red "  FAIL [89] agents/${n}.md still exists on disk; the reviewer rename copied rather than moved, so two definitions now claim one lens"
    FAILED=$((FAILED + 1))
  else
    green "  ok   agents/${n}.md is gone from disk"
  fi
done

# ---------------------------------------------------------------------------
# ABSENT: THE SIX DEAD NAMES, OVER THE WHOLE SCAN SCOPE.
#
# THE BARE NAME IS BANNED, not just the `hackify:`-prefixed dispatch form and not
# just the `agents/<name>.md` path form. The prefixed form is the sharpest defect
# and the path form is the next sharpest, but the bare name is a strict superset
# of both and it also catches the third shape: a frontmatter `name:` key, a
# roster array entry, and prose that sends a reader at a file that is not there.
# Banning the superset costs nothing here because no live file needs to write any
# of these six words, which was measured over the scope below before the list was
# fed to it and is re-measured every run by the scan itself.
#
# THIS IS WHERE [40] AND [89] PART COMPANY ON STRICTNESS, and the reason is that
# their histories differ. [40] bans only the prefixed implementer types, because
# parallel-agents/README.md has to record which types were retired and in which
# version, and dropping the prefix is how that note keeps the record without
# carrying the banned literal. No such note exists for these six: 0.18.0's
# retirement record lives in CHANGELOG.md, which this scope excludes and argues
# for above, so the narrower form would buy nothing and give up the frontmatter
# and path shapes.
#
# The size is hand-written beside the list for the reason RRN_SITES gives.
RRN_DEAD=('code-reviewer-merged' 'code-reviewer-security')
RRN_DEAD+=('code-reviewer-quality-plan' 'code-reviewer-performance')
RRN_DEAD+=('code-reviewer-coherence' 'design-conformance-reviewer')
check_list_size "${#RRN_DEAD[@]}" 6 "the [89] retired reviewer-type ban list"

# THE ORDER OF THESE TWO LISTS IS NOT ASSERTED and does not need to be:
# RRN_OLD_AGENTS above asks whether a FILE exists and RRN_DEAD asks whether a
# WORD survives, so they are the same six strings answering two questions. They
# are written twice rather than aliased because each carries its own hand-written
# bound, and one bound over two meanings is the shape [40]'s WI_BANNED comment
# warns against.

RRN_LIVE_PATHS=(':(top)' ':(top,exclude)dist/*' ':(top,exclude)docs/work/*')
RRN_LIVE_PATHS+=(':(top,exclude)CHANGELOG.md')
RRN_LIVE_PATHS+=(':(top,exclude)scripts/validate-dod.d/89-reviewer-rename.sh')

# STATUS IS GIT GREP'S ALONE, the contract [40]'s wi_absent states and the reason
# it states it: rc 0 is a hit, rc above 1 is a scan that never ran, and rc 1 DOES
# NOT settle the question by itself. git grep returns 1 both for a tree with no
# match and for a scan that could not stat a file it was asked to read. Measured
# there on git 2.50.1: one tracked file at mode 000 gives rc 1, empty stdout and a
# 'Permission denied' line on stderr, while the same file at mode 644 gives rc 1
# with stderr EMPTY. So stderr is the tie-breaker rc alone cannot be, and rc 1
# with anything on stderr is a scan that never ran and must never be the reason a
# dead name prints green.
#
# STDERR GOES TO ITS OWN FILE AND NEVER INTO `hits`. Merging it with `2>&1` would
# let a warning on an otherwise clean scan be read as a matched line, turning a
# clean tree into a phantom hit. `rc=$?` stays the very next statement after the
# substitution so nothing in between can overwrite the status the check rests on.
#
# THE mktemp IS CHECKED, and [40]'s header records what the unchecked version
# cost: a failed mktemp leaves the capture path empty, the redirection then dies
# in the shell BEFORE git runs, and bash hands back 1, which is a status git grep
# itself returns. With no capture file there is no stderr for the tie-breaker to
# read either, so the failure arrives wearing a clean tree's exact face and every
# call fails open at once.
#
# THE TEMP FILE IS TRAPPED AROUND ITS OWN WINDOW, not for the life of the
# fragment, and the clear is a RESTORE rather than a bare `trap - EXIT`. A sourced
# fragment shares one trap table with the whole run, so an EXIT trap left armed
# here would silently replace whatever the next fragment installs, and the tamper
# suite that drives this validator exits through a verdict trap a bare clear would
# delete.
# THE BODY IS rename_absent IN 00-helpers.sh, shared with [40] since the second
# use, and what is left here is the PROFILE. Every branch the paragraphs above
# argue is still what runs, and the canonical argument for each of them sits at the
# head of [40] in 73-implementer-rename.sh, which this was copied from.
#
# ONE MODE, AND IT IS THIS CHECK'S DECISION RATHER THAN A DEFAULT. `untracked`
# means `git grep --untracked`, the worktree plus the files .gitignore does not
# exclude, and no index scan at all. Both halves of that are measured directly
# above and neither survived into the shared body as a hard-coded choice: with one
# mode the verdicts print no mode word, because the word exists to say which half
# of a union spoke and there is no union here.
rrn_absent() {
  RN_ID='[89]'; RN_NOUN='retired reviewer name'; RN_LIST='ban list'
  RN_MODES=(untracked)
  RN_PATHS=(${RRN_LIVE_PATHS[@]+"${RRN_LIVE_PATHS[@]}"})
  rename_absent "$@"
}

# ONE SCAN FOR THE WHOLE BAN LIST, with the per-literal loop above kept as the
# fallback, which is the shape check_no_tokens_in uses in 00-helpers.sh and the
# one [40] adopted after measuring it. The batched grep answers ONLY the yes/no
# question "does anything in this list survive in this scope", and the moment the
# answer is anything but a clean no, the per-literal loop re-runs and words the
# verdict exactly as before. No diagnostic detail is traded for the speed: every
# red this block can print still names WHICH name survived and in WHICH file.
#
# THE SCREEN IS FAIL-CLOSED TOWARD THE SLOW PATH, never toward a green. Only rc 1
# with empty stderr is read as clean. A hit, a scan above rc 1, a scan that wrote
# to stderr, and an mktemp that produced no capture file all fall through to the
# loop, which reaches its own verdict with its own capture file. The screen can
# cost a repeat of the scan; it cannot be the reason a dead name prints green.
#
# -q RATHER THAN -n, since the screen discards output either way, and [40]
# measured that the stderr tie-breaker survives the quiet flag: a sealed tracked
# file returns rc 1 with the same stat error on stderr under -qF as under -nF.
#
# AN EMPTY LIST REFUSES rather than printing nothing, because a screen handed no
# patterns bans nothing while reporting a clean scan.
rrn_absent_all() {
  RN_ID='[89]'; RN_NOUN='retired reviewer name'; RN_LIST='ban list'
  RN_MODES=(untracked)
  RN_PATHS=(${RRN_LIVE_PATHS[@]+"${RRN_LIVE_PATHS[@]}"})
  rename_absent_all "$@"
}

# ---------------------------------------------------------------------------
# THE POSITIVE CONTROL, AND IT IS WHAT MAKES EVERY GREEN ABOVE WORTH READING.
# Everything the absent half prints on a clean tree is a zero, and a zero is
# worth exactly what the scan's ability to have returned non-zero is worth. This
# block shipped without one while [86], [87] and [88] each carried three, and a
# reviewer had to prove by hand, in a throwaway clone, that it could red at all.
# A proof that lives in somebody's transcript is not a proof the next run makes,
# so it is planted here and re-taken on every run.
#
# THE PLANT IS AN UNTRACKED FILE, WHICH IS THE HALF WORTH PROVING. `--untracked`
# is this check's one mode and the whole argument for the block above, so a
# control that could be satisfied by a tracked file would leave exactly the flag
# this fragment exists to justify unproven. Measured before the control was
# written: `git grep --untracked -F -e <literal>` over this scope finds the plant
# at rc 0, and the same scan without the flag returns rc 1 with empty stderr, the
# clean-tree face byte for byte. So a scan that silently lost `--untracked` reds
# here and nowhere else.
#
# THE LITERAL IS NOT A RETIRED REVIEWER NAME, deliberately, and the reason is the
# tree this validator runs in rather than taste. Sibling waves write this same
# working tree while this bar runs, so a plant carrying a banned name would be a
# real dead name on disk for as long as the plant exists, and a concurrent run of
# THIS check would red on it truthfully. A literal that ships nowhere proves the
# same two things, that the scan reaches an untracked file and that the ban
# machinery reddens on a hit, and it is invisible to every other check: it is not
# markdown, so [57] and [80] never see it; it holds no slash command, so [86]
# leaves it alone; and it lives at the repository root, which [55] does not cover.
#
# rrn_absent IS THE CALLER, NOT rrn_absent_all, AND THAT IS THE SECOND THING THIS
# CONTROL BUYS. rrn_absent had no caller at all: the live path runs
# rrn_absent_all, and the shared rename_absent_all re-enters rename_absent
# directly rather than through this fragment's wrapper, so the wrapper was dead
# text that looked like code. Its twin in [40] survives because
# scripts/test_ban_tokens.d/15-wi-absent-cases.sh sed-lifts it by name; nothing
# lifts this one. Calling it here is what makes it live, and it also reaches a
# branch nothing else in this repository reaches: rename_absent's
# `[ "${#RN_MODES[@]}" -gt 1 ]` test in 00-helpers.sh decides whether a
# verdict names the mode that found the hit, and every other caller of it is the
# two-mode [40] profile, so the FALSE side of that test, the one-mode wording,
# ran nowhere. The assertion below reads it directly.
#
# A CONTROL MUST NOT MOVE FAILED, on the rule [83], [87] and [88] all state at
# their own: the counter is read, the judge is called with its printing captured,
# and the counter is put back whatever happened. The DELTA is published rather
# than a yes/no because this control owes exactly one red and a bare "something
# moved" would accept the wrong one.
RRN_CTL_LIT='zzq-89-control-literal-that-ships-nowhere'
RRN_CTL_FILE=".hackify-89-control-$$"
RRN_CTL_DELTA=0
rrn_control_delta() {
  local before="$FAILED"
  rrn_absent "$RRN_CTL_LIT" > "$1" 2>&1
  RRN_CTL_DELTA=$((FAILED - before))
  FAILED="$before"
}

# THE CAPTURE FILE IS CHECKED, for the reason rename_absent checks its own: a
# failed mktemp leaves the redirection target empty, the redirection dies in the
# shell before rrn_absent runs, and the delta comes back 0 wearing the exact face
# of a scan that found nothing. THE PLANT IS REFUSED IF IT IS ALREADY THERE,
# rather than overwritten, because a file of that name means an earlier run died
# between writing it and removing it and a silent overwrite would hide that.
RRN_CTL_OUT=$(mktemp 2> /dev/null) || RRN_CTL_OUT=''
if [ -z "$RRN_CTL_OUT" ]; then
  red "  FAIL [89] the positive control could not create its capture file, so the ban scan below was never measured against a known hit and its silence is not a verdict"
  FAILED=$((FAILED + 1))
elif [ -e "$RRN_CTL_FILE" ]; then
  rm -f "$RRN_CTL_OUT"
  red "  FAIL [89] $RRN_CTL_FILE already exists, so an earlier run died mid-control; remove it by hand rather than letting this overwrite it"
  FAILED=$((FAILED + 1))
else
  printf '%s\n' "$RRN_CTL_LIT" > "$RRN_CTL_FILE"
  rrn_control_delta "$RRN_CTL_OUT"
  rm -f "$RRN_CTL_FILE"
  rrn_ctl_bad=0
  if [ "$RRN_CTL_DELTA" -ne 1 ]; then
    red "  FAIL [89] positive control, a literal planted in an untracked file at the repository root raised $RRN_CTL_DELTA red(s) rather than the 1 it owes; this scan cannot return a dirty result, so every 'survives in no live file' line above was printed by a scan that finds nothing"
    rrn_ctl_bad=1
  elif ! grep -qF -- "$RRN_CTL_FILE" "$RRN_CTL_OUT"; then
    red "  FAIL [89] positive control, the scan reddened but did not name $RRN_CTL_FILE, so it reddened for some reason other than the planted hit and proves nothing about the ban scan"
    rrn_ctl_bad=1
  elif grep -qF 'found by the' "$RRN_CTL_OUT"; then
    red "  FAIL [89] positive control, the verdict attributed the hit to a named scan mode, but this profile declares exactly one mode and that word exists to say which half of a union spoke; a mode word here means RN_MODES has grown a second entry that nothing in this fragment asked for"
    rrn_ctl_bad=1
  fi
  if [ "$rrn_ctl_bad" -eq 0 ]; then
    green "  ok   [89] positive control, a literal planted in an untracked file at the repository root raised the 1 red it owes, named the file it was found in, and named no scan mode, which is the one-mode wording this profile is the only caller of"
  else
    FAILED=$((FAILED + 1))
  fi
  rm -f "$RRN_CTL_OUT"
fi

# THE SCOPE ITSELF IS FLOORED, for the reason [40]'s WI_SCOPE_FLOOR states and
# measures: `git grep -qF -e <anything> -- ':(top)' ':(top,exclude)*'` returns rc 1
# with empty stderr, this block's clean-tree face exactly, so a scope that
# resolved to no file would clear all six names green having read nothing. The
# enumeration matches the SCAN's set rather than the tracked set, --others
# --exclude-standard included, because `--untracked` above reads both and a floor
# over the narrower set would not notice the wider one collapsing. Status is git
# ls-files' alone, no pipe inside the substitution for pipefail to launder and rc
# read next; no stderr capture, because git ls-files has no ambiguous rc 1 to
# break a tie on and its own message is left to print. A floor and not an exact
# count, at roughly half of the 281 files the scope measured when it was written,
# since live files come and go.
RRN_SCOPE_FLOOR=140
rrn_scope_out=$(git ls-files --cached --others --exclude-standard -- "${RRN_LIVE_PATHS[@]}")
rrn_scope_rc=$?
rrn_scope_n=0
while IFS= read -r rrn_scope_f; do
  [ -n "$rrn_scope_f" ] || continue
  rrn_scope_n=$((rrn_scope_n + 1))
done <<RRN_SCOPE_EOF
$rrn_scope_out
RRN_SCOPE_EOF
if [ "$rrn_scope_rc" -ne 0 ] || [ "$rrn_scope_n" -lt "$RRN_SCOPE_FLOOR" ]; then
  red "  FAIL [89] RRN_LIVE_PATHS resolved to $rrn_scope_n live file(s) at rc $rrn_scope_rc, against a floor of $RRN_SCOPE_FLOOR; the scope collapsed rather than the tree shrinking, so the ban scan below would have cleared all ${#RRN_DEAD[@]} names against no file at all"
  FAILED=$((FAILED + 1))
else
  green "  ok   the [89] scan scope resolves to $rrn_scope_n live file(s), at or above its floor of $RRN_SCOPE_FLOOR"
  rrn_absent_all "${RRN_DEAD[@]}"
fi
